### ISSUE TITLE
Upgrade to UE4.26

### ISSUE THREAD

**Issue by DeezeeDigital** [TimmHess/UnrealImageCapture#10]
There's an TArray change to lines 80 & 90 of CameraCaptureManager.cpp.  In UE4.26, IImageWrapper->GetCompressed returns a TArray64, however RunAsyncImageSaveTask digests a TArray.  Need to convert the TArray64 into a TArray to get it working.  I've already made the change on my end and tested it in 4.26.

**Comment by DeezeeDigital** [comment]
Whoops, I see it was updated in the plugin code, but not the project code. :/

**Comment by TimmHess** [comment]
Hey, 
yes, thank you, indeed this is actually suboptimal... I updated the sources :)
