### ISSUE TITLE
Packaging project

### ISSUE THREAD

**Issue by csongorkeller** [TimmHess/UnrealImageCapture#16]
Hi there,
I've tried to package the project but apparently, it doesn't work. This is the error I'm having:
`UATHelper: Packaging (Windows (64-bit)):     CaptureManager.cpp.obj : error LNK2005: "public: __cdecl AsyncSaveImageToDiskTask::~AsyncSaveImageToDiskTask(void)" (??1AsyncSaveImageToDiskTask@@QEAA@XZ) already defined in Module.CameraCaptureToDisk.cpp.obj
UATHelper: Packaging (Windows (64-bit)):     CaptureManager.cpp.obj : error LNK2005: "public: void __cdecl AsyncSaveImageToDiskTask::DoWork(void)" (?DoWork@AsyncSaveImageToDiskTask@@QEAAXXZ) already defined in Module.CameraCaptureToDisk.cpp.obj
UATHelper: Packaging (Windows (64-bit)):        Creating library C:\Users\Administrator\Desktop\UnrealImageCapture-master (1)\UnrealImageCapture-master\CaptureToDisk\Binaries\Win64\CaptureToDisk.lib and object C:\Users\Administrator\Desktop\UnrealImageCapture-master (1)\UnrealImageCapture-master\CaptureToDisk\Binaries\Win64\CaptureToDisk.exp
UATHelper: Packaging (Windows (64-bit)):     C:\Users\Administrator\Desktop\UnrealImageCapture-master (1)\UnrealImageCapture-master\CaptureToDisk\Binaries\Win64\CaptureToDisk.exe : fatal error LNK1169: one or more multiply defined symbols found
UATHelper: Packaging (Windows (64-bit)): Took 18.544797s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool failed. See log for more details. (C:\Users\Administrator\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.26\UBT-CaptureToDisk-Win64-Development.txt)
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults: Error: Unknown Error`

Do you have any idea how I can fix this?

Many thanks in advance

**Comment by TimmHess** [comment]
Hi,

is this your code or the example project? I can take a look at this, but I am short on time atm.. might take a few days.
Quickfix: It seems that maybe the plugin and the code in capture manager are fighting over a symbol, because I dummy copy-pasted it... You can try to rename `AsyncSaveImageToDiskTask` to something fancy in either files. 
At least that is what I get from the linker error you posted.. Even though I would have hoped that the compiler watched that earlier, but it may be worth a try.

**Comment by csongorkeller** [comment]
Hi,
yes. it's the demo project I just pulled down.
Will check if the renaming works, hoping for the best

**Comment by TimmHess** [comment]
Hey,
so it turns out I got the right guess - changing the naming convention fixes the problem for the test project.
