### ISSUE TITLE
cant run project after package

### ISSUE THREAD

**Issue by horsun** [TimmHess/UnrealImageCapture#2]
after add "RHI", "Renderer", "RenderCore" modules,it's can run as editor, but after package ,it cant run ,even dont create any log.

**Comment by horsun** [comment]
ue version 4.23

**Comment by horsun** [comment]
locate here 
`static IImageWrapperModule &ImageWrapperModule = FModuleManager::LoadModuleChecked<IImageWrapperModule>(FName("ImageWrapper"));`

**Comment by TimmHess** [comment]
Hey, thank you very much for pointing this out to me! The bug was in using the IImageWrapperModule  as static, as well as "ImageWrapper" was missing in the public dependencies...

It is now launchable for me, hoping the same is true for you.
