### ISSUE TITLE
Depth & Float Capture?

### ISSUE THREAD

**Issue by aWilson41** [TimmHess/UnrealImageCapture#24]
Does float capture & depth capture work right now? I can't seem to get this working, at least in UE5.0.3. 

The color RGBA capture works fine though.

Read access on `imageWrapper->SetRaw...`

Maybe I configured something wrong?

I think the code creates it own render target and such, but I used:
RenderTarget setup with RGBA16f
SceneCaptureComponent2D setup with HDR in RGB, SceneDepth in A.
CameraCaptureManager setup with UseFloat on and the capture component set. UsePNG off.

**Comment by TimmHess** [comment]
Hey,
yes, they did work.. on multiple occasions I did small updates (see issue history) where I verified them, and just yesterday I tested them for 5.1.0 as well. 

Indeed, the code does overwrite a lot of the SceneCapture's settings so these should not be harmful... 
You did switch functions from CaptureNonBlocking to CaptureFloatNonBlocking?
Also, did you set a PostProcessMaterial that renders the SceneDepth? There is one included in the Plugin (ContentBrowser -> Top Right Corner -> Settings -> Show Plugin Content).
I just tested that and it does not crash for me even when setting not post-process and using float capture but it may be worth a try :/ 

Other than that I need the full crash message and potentially LogError and LogTemp from the log-file located in Saved/Logs

(Minor comment, just to be clear about terminology here -> float is the format I capture depth in. Color and segmentation are stored in standard uint8.)

**Comment by aWilson41** [comment]
Hmm, will give it another go in a couple days. I did use CaptureFloatNonBlocking. I did not use a PostProcessMaterial though, I thought that was only for the stenciling and I didn't want "Segmentations"/annotations yet.

Thanks

**Comment by aWilson41** [comment]
Update from a long while ago. So I got everything working. Depth capture was also being done with post process materials and a particular uasset shader file that is required (because I didn't want to build this project but rather pluck out the code I needed and not have to run it, not realizing that the uasset was involved because it can't be discovered by looking only at the c++ code).

**Comment by aWilson41** [comment]
Maybe it did in UE4 but as far as 5.1.1 goes. I did not find any performance improvements from enqueuing the command. If anything it was slower than just calling capture on the capture component and using ReadPixels.

Which for some bizarre reason, is still incrediably slow in Unreal. Many many many times faster to call read pixels in just raw opengl and such...

I'm sure the non blocking call still helps free up the game from crazy stalls, but doesn't get the image any faster.

**Comment by TimmHess** [comment]
Back at the time all of this was basically to bypass a GPU pipeline flush that was done instead of using the render fences (I guess...). Absolutely possible that it is obsolete by now. 
Do you happen to have a code for reading with opengl calls directly?

**Comment by TimmHess** [comment]
In any case, thanks a lot for sharing your insights! :)

**Comment by aWilson41** [comment]
> Back at the time all of this was basically to bypass a GPU pipeline flush that was done instead of using the render fences (I guess...). Absolutely possible that it is obsolete by now. Do you happen to have a code for reading with opengl calls directly?

I was referring to a standalone opengl program & another opengl renderer not a UE program. Much faster. Still the differences are massive. The timers showed it free'd up the game thread but you receive the image much later. Seems best to just not use Unreal for simulation projects...

**Comment by TimmHess** [comment]
I see... I guess it depends on what you are trying to achieve. If you are indeed able to create a custom-ish engine with the rendering properties that suit your needs - sure. After all I guess what we do is not necessarily "intended use".
For me it was a trade-off between render speed, render quality, and coding overhead and I found that UE is/was very decent for my case, but it definitely comes with some caveats.
