### ISSUE TITLE
Linking error of ACaptureManager.cpp

### ISSUE THREAD

**Issue by Cyanostorm** [TimmHess/UnrealImageCapture#5]
Hi there! I am new to UE4 and I just found your job of solving the image saving stuck problem.
I tried all my best to practice your solution but VS just brought up so much wrong info during the compiling process.

- (1) cannot convert to "const TArray<uint8, FDefaultAllocator> &" from "const TArray<uint8, FDefaultAllocator64>"

- (2) LNK2019	�޷��������ⲿ���� "__declspec(dllimport) public: void __cdecl FRHICommandListImmediate::ReadSurfaceData(class FRHITexture *,struct FIntRect,class TArray<struct FColor,class TSizedDefaultAllocator<32> > &,class FReadSurfaceDataFlags)" (__imp_?ReadSurfaceData@FRHICommandListImmediate@@QEAAXPEAVFRHITexture@@UFIntRect@@AEAV?$TArray@UFColor@@V?$TSizedDefaultAllocator@$0CA@@@@@VFReadSurfaceDataFlags@@@Z)���÷����ں��� "public: void __cdecl ACaptureManager::CaptureColorNonBlocking(class ASceneCapture2D *,bool)" (?CaptureColorNonBlocking@ACaptureManager@@QEAAXPEAVASceneCapture2D@@_N@Z) �б�����	IMUTrial	C:\Users\l00595286\Documents\Unreal Projects\IMUTrial\Intermediate\ProjectFiles\CaptureManager.cpp.obj	1	

Problem (1) happened when ***"const TArray<uint8>& ImgData = imageWrapper->GetCompressed(5);"*** in  **void ACaptureManager::Tick()**  function from **CaptureManager.cpp**. And I solved this by adding a ***const_cast<>*** to force the converting

Problem (2) just cannot be solved and in fact, I do not really kown why there is so much wierd symbols instead of showing English.

I also tried to copy your code into my game project(I have adapted it to suit my running environment), but the same error happened and I just don't know what I can do about that.

**Comment by TimmHess** [comment]
Hey, 
(1) is strange.. I will need to take a closer look.

(2) Did this happen in the provided test project? This very much seems like issue #3 I should update the tutorial  on that part :see_no_evil:

**Comment by TimmHess** [comment]
Hey,

(1) is strange, I will need to take a closer look.

(2) seems like issue #3 - Does that help? I should update the tutorial on that part :see_no_evil:

**Comment by TimmHess** [comment]
To (1): Is this "const TArray& ImgData = imageWrapper->GetCompressed(5);" the exact line in your code? Not const "TArray**<uint8>**& ImgData = imageWrapper->GetCompressed(5);" to specify the uint8 type?

I mean you fixed it anyways, just wanted to throw this in because it did yet not received this error :D

**Comment by Cyanostorm** [comment]
> Hey,
> 
> (1) is strange, I will need to take a closer look.
> 
> (2) seems like issue #3 - Does that help? I should update the tutorial on that part 🙈

Hi！I am so sorry for not replying your message in time.  And so much thanks that Issue #3 solves my problem during linking through adding necessary libs in **.Build.cs** file. I learned a lot from your project and thank you for your patience.

As for problem (1), I still feel so confused why VS log the error **_cannot convert to "const TArray<uint8, FDefaultAllocator> &" from "const TArray<uint8, FDefaultAllocator64>"_**.
My code writes `const TArray<uint8>& ImgData = imageWrapper->GetCompressed(5);` exactly the same as the line in your CaptureManager.cpp file in private folder, and the same error happend when I copied your code into my VS project. I have searched in google to find other people's usage of the TArray<uint8> in UE4, and it seems that everybody just do not need an extra force converting at all, but I have to add a static_cast<> to convert the type.

**Comment by Cyanostorm** [comment]
The following is a fragment of my code:
```
if (nextRenderRequest) { //nullptr check
			if (nextRenderRequest->RenderFence.IsFenceComplete()) { // Check if rendering is done, indicated by RenderFence

				// Load the image wrapper module 
				IImageWrapperModule& ImageWrapperModule = FModuleManager::LoadModuleChecked<IImageWrapperModule>(FName("ImageWrapper"));

				// Decide storing of data, either jpeg or png
				if (nextRenderRequest->isPNG) {
					//Generate image name
					FString fileName = FPaths::ProjectSavedDir() + "mask";  // ABindingSocketCharacter::IMUSensor::OutFile + "\\renderImages"
					fileName += ".png"; // Add file ending

					// Prepare data to be written to disk
					static TSharedPtr<IImageWrapper> imageWrapper = ImageWrapperModule.CreateImageWrapper(EImageFormat::PNG); //EImageFormat::PNG //EImageFormat::JPEG
					imageWrapper->SetRaw(nextRenderRequest->Image.GetData(), nextRenderRequest->Image.GetAllocatedSize(), frameWidth, frameHeight, ERGBFormat::BGRA, 8);
                                       
					//const TArray<uint8>& ImgData = imageWrapper->GetCompressed(5);  // where error happens
					const TArray<uint8>& ImgData = static_cast<TArray<uint8, FDefaultAllocator>>(imageWrapper->GetCompressed(5));
					RunAsyncImageSaveTask(ImgData, fileName);
				}
				else {
					UE_LOG(LogTemp, Log, TEXT("Started Saving Color Image"));

                                .........
                                }
```

**Comment by Cyanostorm** [comment]
I just found another confusing thing. In the turotial, you said that 

> The component I am using for capturing is the SceneCaptureComponent2D provided as default by the UE4Editor. Placing one of these into your scene will give you a ASceneCaptureComponent which is its Actor instance.

I just do not understand how I can place an `ASceneCapture2D`

**Comment by TimmHess** [comment]
No worries, great that it compiles now! :)

I actually have no clue what is causing the TArray issue... is the static cast super slow? otherwise, I guess it will suit the need for now?

From the left side of the editor menu you can place a 'SceneCaptureComponent2D' into your scene. (Sorry I currently have no engine in front of me :see_no_evil: ) In your CaptureManager (which is likewise a component placed in the scene) you should then be able to select this SceneCaptureComponent from the respective dropdown menu. 
The ASceneCapture2D class simply interfaces components _placed_ in the scene in code.
Generally, as far as I understood, for C++ classes in UE4 a prefix "A" addresses an 'Actor', i.e. an actual instance of an object/component in the world, where a prefix "U" addresses the interface without a specific instance. Hoping to not confuse or getting it wrong.

**Comment by benjamin-lange** [comment]
I had the same issue.
and going from:
`const TArray<uint8>& ImgData = imageWrapper->GetCompressed(0);`
to:
`const TArray<uint8>& ImgData = static_cast<TArray<uint8, FDefaultAllocator>>(imageWrapper->GetCompressed(0));`
fixed it.

If anyone ever finds out why this has to be done, I'd like to know. 🃏

**Comment by TimmHess** [comment]
Okay, the error's origin is that as of engine version 4.25 the output of `imageWrapper->GetCompressed()` switched from TArray<...> to TArray64<...>, as suggested by the error message. 
Of course, the fix you already suggested works, alternatively you could switch all TArray to TArray64 to omit the conversion.. I do not know whether there is a trade-off in either approach :)
