### ISSUE TITLE
Save raw scene depth values to disk

### ISSUE THREAD

**Issue by benjamin-lange** [TimmHess/UnrealImageCapture#7]
Hey there,

I was wondering if you could point me in right direction of using your code to access the raw scene depth (as given by the "Scene Depth" node in the material editor) and save it to disk.

I managed to get a 0-255 grayscaled depth image using a post processing material, but I could not manage yet to get a hold of the scene depth using Blueprint or C++, since the raw scene has a much higher precision than my approach.

One would have to access the gbuffer somehow, but I could not find any good resource on that topic yet.

Any hints are much appreciated.

**Comment by TimmHess** [comment]
Hey, there is an implementation for that in UnrealCV and AirSim which I adapted. Disclaimer: This for some reason worked only using the Vulkan, on DX11 and DX12 I got crashes on the GPU thread that I could not yet track down but would be highly interested in resolving...

The main idea is to capture .EXR data, which supports float16 values. I later loaded them with a python exr lib.

First, you need to change Source(SceneCapture) and the RenderTarget to:
 ```
 CaptureComponent->CaptureSource = ESceneCaptureSource::SCS_SceneDepth;
  // Set RenderTarget to use FloatOutput
  RenderTarget->InitCustomFormat(FrameWidth, FrameHeight, PF_FloatRGBA, true);
  // Set RenderTargetTexture to use Float16
  RenderTarget->RenderTargetFormat = ETextureRenderTargetFormat::RTF_RGBA16f;
```

Then you can witch your surface reading context to:
```
struct FReadSurfaceFloatContext
    {
        FRenderTarget* SrcRenderTarget;
        TArray<FFloat16Color>* OutData;
        FIntRect Rect;
        ECubeFace CubeFace;
    };
```
and enqueue the render command (sorry for the pre 4.22 version)
```
TArray<FFloat16Color> SurfaceData;
    FReadSurfaceFloatContext ReadSurfaceFloatContext =
    {
        renderTargetResource,
        &SurfaceData,
        FIntRect(0, 0, renderTargetResource->GetSizeXY().X, renderTargetResource->GetSizeXY().Y),
        CubeFace
    };

ENQUEUE_UNIQUE_RENDER_COMMAND_ONEPARAMETER(
        ReadSurfaceFloatCommand,
        FReadSurfaceFloatContext,Context,ReadSurfaceFloatContext,
    {
        RHICmdList.ReadSurfaceFloatData(
            Context.SrcRenderTarget->GetRenderTargetTexture(),
            Context.Rect,
            *Context.OutData,
            Context.CubeFace,
            0,
            0
            );
    });
```

The remainder code is still highly experimental, but maybe you can get something out of it.

This was necessary to read the data to the float16 array:
```
TArray<FFloat16Color> OutImageData;
OutImageData.AddUninitialized(ImageWidth*ImageHeight);

TArray<FFloat16Color>& OutImagePtr = OutImageData; // stupid hack

// Copy the surface data into the output array.
FFloat16Color* OutImageColors = reinterpret_cast< FFloat16Color* >((FFloat16Color*)&(OutImagePtr[0]));

// Cache width and height as its very expensive to call these virtuals in inner loop (never inlined)
const int32 ImageWidth = renderTargetResource->GetSizeXY().X;
const int32 ImageHeight = renderTargetResource->GetSizeXY().Y;
for (int32 Y = 0; Y < ImageHeight; Y++){
    FFloat16Color* SourceData = (FFloat16Color*) SurfaceData.GetData() + Y * ImageWidth;
    for (int32 X = 0; X < ImageWidth; X++){
        OutImageColors[ Y * ImageWidth + X ] = SourceData[X];
    }
}
```

Where then finally you can write it using the ImageWrapper module:
```
static IImageWrapperModule& ImageWrapperModule = FModuleManager::LoadModuleChecked<IImageWrapperModule>(FName("ImageWrapper"));
static TSharedPtr<IImageWrapper> ImageWrapper = ImageWrapperModule.CreateImageWrapper(EImageFormat::EXR);

ImageWrapper->SetRaw(OutImageData.GetData(), OutImageData.GetAllocatedSize(), FrameWidth, FrameHeight, ERGBFormat::RGBA, 16);
```

**Comment by benjamin-lange** [comment]
Wow! Thank you so much for a detailed and speedy answer. 🏆 I am going to try it out.

If you are interested here is the post processing material for the rather coarse depth information, the advantage is you can view it with a normal image viewer:
![simple_depth_ppm](https://user-images.githubusercontent.com/37362568/109183394-300aaf00-778e-11eb-9712-d7c3a7c65124.PNG)

**Comment by TimmHess** [comment]
No worries and thanks! 
Let's see how far it will get you ;) I hope you can solve the problem..  maybe let me know if you do, because I would really be interested in why this keeps crashing on me in windows.. and of course, let me know if I can be of any further help.

**Comment by TimmHess** [comment]
Okay.. now there should be non-blocking float-valued depth capture support to .exr, which is currently integrated into the non-packed plugin version: 

[https://github.com/TimmHess/UnrealImageCapture/blob/master/CaptureToDisk/Plugins/CameraCaptureToDisk/Source/CameraCaptureToDisk/Private/CameraCaptureManager.cpp](url)

In my tests it seemingly worked as expected ;) I validated it with python OpenEXR.
